<template>
  <div class="wrap">
    <h1>更新日志</h1>
    <h2>2017-06-19</h2>
    <ul>
      <li>优化了答案匹配机制</li>
      <li>答案窗口，新增“采纳我的答案”按钮</li>
      <li>新增了3个字体图标</li>
    </ul>
    <h2>2017-02-03</h2>
    <ul>
      <li>增加上传进度条和拖拽上传</li>
      <li>将依赖包更新到最新版本</li>
      <li>优化了用户体验</li>
    </ul>
    <h2>2017-02-01</h2>
    <ul>
      <li>对Ajax请求进行了封装，使代码更简洁</li>
      <li>优化了获取随机剧照的算法，避免了出现重复剧照的bug</li>
      <li>优化了报错机制，减少了宕机的几率</li>
      <li>优化了登录和注册的验证机制</li>
    </ul>
    <h2>2017-01-02</h2>
    <ul>
      <li>使用es2015标准对JavaScript代码进行了梳理，并修复了一些bug</li>
      <li>使用ESLint对JavaScript进行代码规范校验</li>
    </ul>
    <h2>2016-11-29</h2>
    <ul>
      <li>增加用户，登录、注册、答题记录、上传记录</li>
      <li>由于页面复杂度提高，Vue-router替换了现有的简单路由</li>
    </ul>
    <h2>2016-11-11</h2>
    <ul>
      <li>修复了在线图片点击两次才能上传的bug</li>
    </ul>
    <h2>2016-11-10</h2>
    <ul>
      <li>删掉了多余的组件</li>
      <li>将Vue-router替换为更简单的路由</li>
      <li>element-ui 更新到1.0稳定版</li>
      <li>引入babel-plugin-component，按需引入element组建，打包后的体积减少了300多kb</li>
      <li>新增 about 页面</li>
    </ul>
    <h2>2016-11-09</h2>
    <ul>
      <li>增加了跳过功能</li>
      <li>完善了答案判断机制</li>
      <li>默认读取压缩后的图片</li>
    </ul>
    <h2>2016-11-08</h2>
    <ul>
      <li>新增了剧照审核功能，新上传的剧照必须过审才能显示到首页</li>
      <li>新增了非图片（包含防盗链图片）过滤功能</li>
      <li>新增了答案判断机制</li>
    </ul>
    <h2>2016-11-07</h2>
    <ul>
      <li>部署到到服务器，正式上线</li>
      <li>修复了上传按钮的显示问题，并将其改名为“提交”</li>
      <li>新增了上传小提示</li>
    </ul>
    <h1>意见反馈</h1>
    <p>有任何意见或建议，欢迎反馈到：<a href="mailto:rossromay@gmail.com">rossromay@gmail.com</a>，或到github提交issues：<a href="https://github.com/rossroma/movie/issues">Movie</a></p>
  </div>
</template>